name = "Muon"
uuid = "446846d7-b4ce-489d-bf74-72da18fe3629"
authors = ["Danila Bredikhin <danila.bredikhin@embl.de>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
